columnSuffix: null
handle: description
instructions: 'Add body text here.'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: 250
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Please add text.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
