columnSuffix: null
handle: heroImage
instructions: 'add the Hero Image here.'
name: 'Hero Afbeelding'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:f28c5aef-a3e8-41b3-8623-2ba3f42c7cb7' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f28c5aef-a3e8-41b3-8623-2ba3f42c7cb7' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Afbeelding toevoegen'
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: true
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
