columnSuffix: null
handle: Instagram
instructions: 'Add a Social Media Global Link here'
name: social-link
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
