dateModified: 1714563556
email:
  fromEmail: 12201074@student.pxl.be
  fromName: WebExpert-Craft
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Afbeeldingen
    settings:
      path: '@webroot/files'
    type: craft\fs\Local
    url: /files
  video:
    hasUrls: true
    name: Video
    settings:
      path: web/uploads
    type: craft\fs\Local
    url: '@webroot/uploads'
meta:
  __names__:
    9d3c309c-cbb1-484c-aa76-6c735b16d4ab: 'Public Schema' # Public Schema
    9e6c42b3-24b7-4f14-aae1-0221bff9b1fe: textfield # textfield
    23b3049d-9371-4642-b736-675121176002: about-content # about-content
    58b4db94-c28e-4425-aa99-3d6acfe2b619: Intro # Intro
    69e8880e-4349-4104-8c10-fcf3553ad1ee: WebExpert-Craft # WebExpert-Craft
    498ef8e8-ab5a-49e8-b3a2-dc96897059e6: imagetest # imagetest
    5194dbae-7b49-4fe0-967a-f57bded8e82f: Blog # Blog
    30150ce9-3e49-4ef5-a72c-62c684180f6e: WebExpert-Craft # WebExpert-Craft
    a2cdcb91-aee9-4962-b096-6d0040272d44: Homepage # Homepage
    b9e04d0e-62af-4434-a28e-0cb9109b2cae: about # about
    beb3fdc0-71d2-47a1-9e92-c6c0a0fd01ed: Titel # Titel
    c55c23ca-6ec1-479c-8438-0f70fce3a3be: startpagina # startpagina
    ca6b0345-14c9-4d36-8a96-ff70fb2cad05: 'Hero Afbeelding' # Hero Afbeelding
    e18eb04b-759e-41cb-a454-42138a30c16d: blogposttest # blogposttest
    f28c5aef-a3e8-41b3-8623-2ba3f42c7cb7: Images # Images
    ff53dd1b-b693-4840-93bb-83c470eea8f8: Subtitle # Subtitle
system:
  edition: team
  live: true
  name: WebExpert-Craft
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
