fieldLayouts:
  322faa1d-03e5-48e6-bdde-e71cd84620cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c943c780-4da5-4a19-aed3-c331dabf027f # social-link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84d6dce7-2246-482a-9344-e8c7aa5703b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c943c780-4da5-4a19-aed3-c331dabf027f # social-link
            handle: Facebook
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b14533f7-cf6f-444e-87a0-886cae1c09ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c943c780-4da5-4a19-aed3-c331dabf027f # social-link
            handle: LinkedIn
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b30e17c-3fdb-4d97-b2b9-5c79492673ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c943c780-4da5-4a19-aed3-c331dabf027f # social-link
            handle: Twitter
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4163c6c-a174-46ea-b64f-fad4feddf354
            userCondition: null
            warning: null
            width: 100
        name: Links
        uid: 062c12a2-bcec-46b1-b370-40b2c787b16a
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 1
