defaultPlacement: end
enableVersioning: true
entryTypes:
  - c55c23ca-6ec1-479c-8438-0f70fce3a3be # startpagina
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30150ce9-3e49-4ef5-a72c-62c684180f6e: # WebExpert-Craft
    enabledByDefault: true
    hasUrls: true
    template: home-page.twig
    uriFormat: __home__
type: single
